anchore/sbom-action

.github/workflows/update-syft-release.yml

This fixes #191 - adds a periodic check for updated Syft versions, which should create a PR (and run tests/etc.). Note: this is dependent on the `SyftVersion.ts` change from #201

Add a Syft release check, automatically create a PR

---

dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/GithubClient.ts
src/github/SyftGithubAction.ts
tests/GithubClient.test.ts

There was an error reported during a dependency snapshot upload:
```
Error: Converting circular structure to JSON
149
--> starting at object with constructor 'TLSSocket'
150
|     property '_httpMessage' -> object with constructor 'ClientRequest'
151
--- property 'socket' closes the circle
```
I have not been able to reproduce this, but I suspect there was a legitimate error during upload which is getting masked by a circular reference stringifying error, this PR replaces all `JSON.stringify` calls used for logging with `console.log` calls.

Don't use JSON.stringify for logging purposes

---

.github/workflows/update-syft-release.yml

As the title says: secrets have been moved to org-level for the auto-update script; this should use the new keys.

Update secret parameter names

---

.github/workflows/update-syft-release.yml

The Syft auto-update will fail for any forks, we just want it running in the main repo.

Only run Syft auto-update in main repo

---

.github/release-drafter.yml

Syft and Grype have an author in the release notes automatically, we should add that to the release drafter template here, too.
See release-drafter docs: https://github.com/marketplace/actions/release-drafter#change-template-variables

Add author to the release drafter template

---

README.md
action.yml
dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/Syft.ts
src/github/SyftGithubAction.ts

Signed-off-by: Malte Poll <mp@edgeless.systems>

Allow type "file:..." to enable creation of SBOMs from tar and other package formats

---

dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/SyftGithubAction.ts
tests/SyftGithubAction.test.ts

This PR corrects an issue where the `file` input was not functioning properly and adds tests to validate each input type of `file`, `path`, and `image`.
Fixes #383

File input not being passed properly to Syft invocation

---

dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/SyftGithubAction.ts

👋🏽 from the Dependency Graph team at GitHub!
I've been working on some functionality related to dependency snapshots on pull requests, and I've discovered an unfortunate fact about the behavior of `github.context.sha`/`$GITHUB_SHA` in that context.
Evidently, `github.context.sha` is not always what you might consider the "current commit" in a given context. In most GitHub pull request event types, `github.context.sha` will be the "Last merge commit on the GITHUB_REF branch" (See [Actions documentation here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)). In those cases, the commit SHA that should be associated with the snapshot is `github.event.pull_request.head.sha`.
This PR adds a helper function, `getSha`, which will return the correct …

Use the correct SHA for dependency snapshots from pull requests

---

.github/workflows/test.yml
README.md
action.yml
dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
package-lock.json
src/github/GithubClient.ts
src/github/SyftGithubAction.ts
tests/GithubClient.test.ts
tests/SyftGithubAction.test.ts
tests/mocks.ts

- added new input to support retention of workflow artifact
- updated Action `Vampire/setup-wsl` to `v2`
- added missed inputs in readme
- updated  dependency `http-cache-semantics` to `4.1.1` (https://github.com/advisories/GHSA-rc47-6667-2j5j)
- added unit tests for new input

[FEATURE] Added support of workflow artifact's retention policy

---

.github/workflows/update-syft-release.yml

When unauthenticated rate limits are reached, the Syft version check returns `null` and we get PRs like https://github.com/anchore/sbom-action/pull/404 . By adding a token, we get per-repository rate limits that are much higher (and we're only using this once or a few times a day).

chore: add github token to syft update check

---

.github/workflows/update-snapshots.yml

This PR adds a workflow that triggers when `/update-snapshots` comment is made on a PR that runs the `npm run test:update-snaphshots` and pushes to the PR branch, triggering test workflows to be re-run.

chore: add workflow to update snapshots from PR comment

---

.github/workflows/update-syft-release.yml

Update deprecated `::set-output` calls

chore: update deprecated set-output calls

---

dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/SyftGithubAction.ts

Before this, the sbom file would only be copied to `output-file` if `upload-artifact` is true. However, the file may still be useful if upload is not enabled.

fix: ensure sbom is copied to `output-file`

---

README.md
action.yml
dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/Syft.ts
src/github/SyftGithubAction.ts
tests/SyftGithubAction.test.ts

Allow a Syft configuration file to be passed to the action.

Add config input

---

.github/workflows/update-snapshots.yml

According to the relesae notes, github.* API methods have been removed and should instead by accessed by github.rest.*. Use that method to access pull request information.
See https://github.com/marketplace/actions/github-script#v5

chore: fix github-script invocation

---

dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/SyftGithubAction.ts
tests/SyftGithubAction.test.ts

When executing Syft, we don't need to have debug logging enabled by default.
Fixes #445

fix: reduce syft debug level

---

DEVELOPING.md
dist/attachReleaseAssets/index.js
dist/downloadSyft/index.js
dist/runSyftAction/index.js
src/github/SyftGithubAction.ts

Signed-off-by: Noah Krause <krausenoah@gmail.com>

fix: don't pass in a separate env. This makes it impossible to pass env vars via the action context to syft.

---

.github/workflows/test.yml
package-lock.json
package.json
src/github/GithubClient.ts
src/github/SyftGithubAction.ts
tests/GithubClient.test.ts
tests/SyftGithubAction.test.ts
tests/integration/formatExports.test.ts
tests/mocks.ts

This PR updates the `@actions/artifact` library to the most recent version, which includes some usage updates.
See test runs here:
* https://github.com/kzantow-anchore/sbom-action-test/actions/runs/8943293414/job/24567681706#step:4:17
* Artifacts attached: https://github.com/kzantow-anchore/sbom-action-test/actions/runs/8943293414
* Snapshot successful: https://github.com/kzantow-anchore/sbom-action-test/actions/runs/8943293414/job/24567681706#step:4:979
* Release asset attached:
* Current workflow list succeeded: https://github.com/kzantow-anchore/sbom-action-test/actions/runs/8943319048/job/24567762793#step:2:752
* Asset attached: https://github.com/kzantow-anchore/sbom-action-test/releases/tag/v15
... I think that covers the attachment integration points. And, of course, there are …

chore: update GitHub artifact client

---

README.md

A recent update to the GitHub actions toolkit had an impact on a couple aspects of workflow artifact usage, this PR updates the docs with information that should get anyone unblocked who has issues with these changes.
See:
* https://github.com/anchore/sbom-action/issues/467
* https://github.com/anchore/sbom-action/issues/468

docs: notes for matrix and required permissions

---

src/github/SyftGithubAction.ts

Fixes #389
This PR reorders conditional logic that appends image/dir/file information to the syft command such that the `file` input to the action is parsed before the `path` input.
The `path` input has a default value (see: https://github.com/anchore/sbom-action/blob/main/action.yml#L11), and the conditional logic (modified in this PR) would see the path value is set to `.` (even if the user didn't provide a value) and add it to the run command. This is short-circuiting the if/else, so nothing else (in the same block) gets included in the run command.

fix: allow users to properly use the file input over the default path value

---

src/github/SyftGithubAction.ts

Because of a small bug the version of curl presently on GitHub windows runners, Syft's install.sh file can fail to execute. Therefore, at least for now, fall back to just using cache.downloadTool to get Syft.
Fixes https://github.com/anchore/sbom-action/issues/472

fix: workaround windows install script

---

package.json

Previously, running the npm test script in CI would sometimes result in multiple test processes all trying to install Syft at the same time, and one would fail with "span: ETXTBSY". Instead, run all tests in series.
See https://jestjs.io/docs/cli#--runinband
See anchore/scan-action#265

chore: serialize tests to prevent install race

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.md

Creates a comprehensive issue template (based on the super-linter one).
It might be a touch *too* comprehensive, and have the adverse effect of making people less likely to file an issue?

chore: Create issue template

---

README.md

This updates the links to the community Slack to Discourse links.

doc: Updates for the Slack to Discourse migration

---

README.md

Currently the info about permissions is below the fold, and I missed it when implementing the action for my own projects.

Update README to include bit about permissions near the top
